Debug release assets

diff --git a/.github/workflows/build-idx.yml b/.github/workflows/build-idx.yml
--- a/.github/workflows/build-idx.yml
+++ b/.github/workflows/build-idx.yml
@@ -19,6 +19,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      # Download latest stable version of tools from github.com/adjust/cli-tools.
+      - name: Get Tools
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          curl -sLO https://github.com/cli/cli/releases/download/v2.83.2/gh_2.83.2_linux_amd64.tar.gz && tar xzvf gh_2.83.2_linux_amd64.tar.gz --strip-components 2 gh_2.83.2_linux_amd64/bin/gh
+          gh_hash=$(git hash-object ./gh)
+          [ "$gh_hash" == "2c250e2c82c3d6a132df5af5ae423c96902211df" ] || (echo "::error::unexpected hash for gh, possible tampering: $gh_hash" && exit 1)
+
       - name: Install ipinfo
         run: |
           go install .
@@ -35,14 +44,8 @@ jobs:
 
       - name: Upload cloud.bin
         if: hashFiles('cloud.bin') != ''
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: "https://uploads.github.com/repos/vearutop/ipinfo/releases/272330670/assets{?name,label}"
-          asset_path: ./cloud.bin
-          asset_name: cloud.bin
-          asset_content_type: application/octet-stream
+        run: |
+          ./gh release upload --clobber index cloud.bin
 
       - name: Build ASN lite
         run: |
